sudo: required
dist: bionic
language:
  - python
python:
  - "3.8"
addons:
  apt:
    update: true
    packages:
      - python3.8-dev

cache:
  directories:
    - $HOME/.cache/bazel

env:
  - USE_BAZEL_VERSION=3.7.0

install:
  - curl -LJo $HOME/bin/buildifier https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier
  - chmod +x $HOME/bin/buildifier
  - curl -LJo $HOME/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64
  - chmod +x $HOME/bin/bazel
  - pip install black==20.8b1
  - pip uninstall -y pip setuptools wheels

script:
  # Check for issues with the format of our bazel and python code.
  - buildifier -mode=check $(find . -type f -name '*.bzl' -o -name WORKSPACE -o -name BUILD)
  - black --check --exclude 'third_party' .
  # Check that all of our tests pass
  - bazel info
  - bazel clean && bazel test --config=ci //...
  - cd examples; bazel clean && bazel test --config=ci //...
